name: INNOVATE_AI_WEBSITE

on:
  push:
    branches:
      - develop

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

  Deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
           PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
           HOSTNAME : ${{ secrets.HOSTNAME  }}
           USER_NAME : ${{ secrets.USER_NAME  }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
             cd innovate-ai-website
             docker system prune -f
             git fetch -p
             git pull origin develop
             docker-compose down
             docker-compose up -d --build
             docker ps -a
          ' 